package com.phq9_final.phq9final;

rule "PHQ-9-Rule_1"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ5>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_2"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ6>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_3"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ7>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_4"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_5"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_6"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ6>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_7"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ7>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_8"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_9"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_10"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ6>=2 && PHQQ7>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_11"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ6>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_12"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ6>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_13"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_14"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_15"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_16"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ6>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_17"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ7>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_18"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_19"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_20"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ6>=2 && PHQQ7>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_21"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ6>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_22"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ6>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_23"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_24"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_25"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_26"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ5>=2 && PHQQ6>=2 && PHQQ7>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_27"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ5>=2 && PHQQ6>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_28"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ5>=2 && PHQQ6>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_29"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ5>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_30"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ5>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_31"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ5>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_32"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ6>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_33"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ6>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_34"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ6>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_35"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 && PHQQ2>=2 )
		PHQ9Qa: PHQ9Q(PHQQ7>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_36"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ5>=2 && PHQQ6>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_37"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ5>=2 && PHQQ7>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_38"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ5>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_39"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ5>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_40"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ6>=2 && PHQQ7>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_41"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ6>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_42"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ6>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_43"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_44"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_45"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_46"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ7>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_47"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_48"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_49"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_50"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_51"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_52"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_53"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_54"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ6>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_55"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ7>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_56"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ7>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_57"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_58"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_59"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_60"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_61"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_62"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_63"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_64"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ6>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_65"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ7>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_66"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ5>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_67"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ5>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_68"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ5>=2 && PHQQ6>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_69"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ5>=2 && PHQQ7>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_70"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ6>=2 && PHQQ7>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_71"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ5>=2 && PHQQ6>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_72"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ5>=2 && PHQQ7>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_73"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ5>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_74"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ5>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_75"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ6>=2 && PHQQ7>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_76"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ6>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_77"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ6>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_78"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_79"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_80"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_81"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ7>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_82"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_83"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_84"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_85"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_86"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_87"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_88"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_89"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ6>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_90"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ7>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_91"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ7>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_92"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_93"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_94"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_95"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_96"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_97"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_98"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_99"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ6>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_100"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ7>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_101"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ5>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_102"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ5>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_103"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ5>=2 && PHQQ6>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_104"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ5>=2 && PHQQ7>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_105"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ2Qa: PHQ2Q(PHQQ1>=2 )
		PHQ9Qa: PHQ9Q(PHQQ6>=2 && PHQQ7>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_106"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ7>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_107"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_108"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_109"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ5>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_110"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ5>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_111"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ5>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_112"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_113"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_114"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ6>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_115"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ4>=2 && PHQQ7>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_116"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_117"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_118"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_119"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ5>=2 && PHQQ7>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_120"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ3>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_121"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ8>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_122"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_123"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ6>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_124"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ5>=2 && PHQQ7>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_125"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ4>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end

rule "PHQ-9-Rule_126"
	dialect "mvel"
	ruleflow-group "PHQ-9-Rule"
	when
		PHQ9Qa: PHQ9Q(PHQQ5>=2 && PHQQ6>=2 && PHQQ7>=2 && PHQQ8>=2 && PHQQ9>=2 )
	then
		PHQ9R fact1 = new PHQ9R();
		fact1.setPHQ9Result(true);
		insert(fact1);
end
