package com.phq9_final.phq9final;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PHQ2R implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean PHQ2Result;

	public PHQ2R() {
	}

	public java.lang.Boolean getPHQ2Result() {
		return this.PHQ2Result;
	}

	public void setPHQ2Result(java.lang.Boolean PHQ2Result) {
		this.PHQ2Result = PHQ2Result;
	}

	public PHQ2R(java.lang.Boolean PHQ2Result) {
		this.PHQ2Result = PHQ2Result;
	}

}