package com.phq9_final.phq9final;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PHQ9R implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean PHQ9Result;

	public PHQ9R() {
	}

	public java.lang.Boolean getPHQ9Result() {
		return this.PHQ9Result;
	}

	public void setPHQ9Result(java.lang.Boolean PHQ9Result) {
		this.PHQ9Result = PHQ9Result;
	}

	public PHQ9R(java.lang.Boolean PHQ9Result) {
		this.PHQ9Result = PHQ9Result;
	}

}