package com.phq9_final.phq9final;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PreScreenR implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean preScreenResult;

	public PreScreenR() {
	}

	public java.lang.Boolean getPreScreenResult() {
		return this.preScreenResult;
	}

	public void setPreScreenResult(java.lang.Boolean preScreenResult) {
		this.preScreenResult = preScreenResult;
	}

	public PreScreenR(java.lang.Boolean preScreenResult) {
		this.preScreenResult = preScreenResult;
	}

}