package com.phq9_final.phq9final;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Treatment3 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean treat3;

	public Treatment3() {
	}

	public java.lang.Boolean getTreat3() {
		return this.treat3;
	}

	public void setTreat3(java.lang.Boolean treat3) {
		this.treat3 = treat3;
	}

	public Treatment3(java.lang.Boolean treat3) {
		this.treat3 = treat3;
	}

}