package com.phq9_final.phq9final;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PHQ2Q implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Double PHQQ1;
	private java.lang.Double PHQQ2;

	public PHQ2Q() {
	}

	public java.lang.Double getPHQQ1() {
		return this.PHQQ1;
	}

	public void setPHQQ1(java.lang.Double PHQQ1) {
		this.PHQQ1 = PHQQ1;
	}

	public java.lang.Double getPHQQ2() {
		return this.PHQQ2;
	}

	public void setPHQQ2(java.lang.Double PHQQ2) {
		this.PHQQ2 = PHQQ2;
	}

	public int getTotalInBlue() {
		int inBlue = 0;
		if (this.PHQQ1 >= 2) {
			inBlue++;
		}
		if (this.PHQQ2 >= 2) {
			inBlue++;
		}

		return inBlue;
	}

	public PHQ2Q(java.lang.Double PHQQ1, java.lang.Double PHQQ2) {
		this.PHQQ1 = PHQQ1;
		this.PHQQ2 = PHQQ2;
	}
	
	

}