package com.phq9_final.phq9final;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Treatment1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean treat1;

	public Treatment1() {
	}

	public java.lang.Boolean getTreat1() {
		return this.treat1;
	}

	public void setTreat1(java.lang.Boolean treat1) {
		this.treat1 = treat1;
	}

	public Treatment1(java.lang.Boolean treat1) {
		this.treat1 = treat1;
	}

}