package com.phq9_final.phq9final;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Treatment2 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean treat2;

	public Treatment2() {
	}

	public java.lang.Boolean getTreat2() {
		return this.treat2;
	}

	public void setTreat2(java.lang.Boolean treat2) {
		this.treat2 = treat2;
	}

	public Treatment2(java.lang.Boolean treat2) {
		this.treat2 = treat2;
	}

}